# Generated by Django 5.2.5 on 2025-09-16 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohlag', '0001_initial'),
        ('tablas', '0014_delete_activos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos',
            name='tipo',
            field=models.CharField(choices=[('0', 'ALL'), ('1', 'IT'), ('2', 'MO')], default='1', max_length=1),
        ),
        migrations.CreateModel(
            name='AdminPaises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_pais', to='tablas.paises')),
                ('paisadmin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_paisadmin', to='tablas.paises')),
            ],
            options={
                'db_table': 'hlag_adminpaises',
                'ordering': ['pais', 'paisadmin'],
            },
        ),
    ]
