# Generated by Django 5.2.5 on 2025-09-16 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohlag', '0003_areas_delete_adminpaises'),
        ('tablas', '0016_nombresareas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas',
            options={'ordering': ['areaname', 'pais']},
        ),
        migrations.RemoveField(
            model_name='areas',
            name='nombre',
        ),
        migrations.AddField(
            model_name='areas',
            name='areaname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablas.nombresareas'),
        ),
        migrations.AlterField(
            model_name='areas',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablas.paises'),
        ),
    ]
