# Generated by Django 5.2.5 on 2025-09-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohlag', '0004_alter_areas_options_remove_areas_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activos',
            options={'ordering': ['tipo', 'identificador', 'nombre', 'modelo', 'fabricante', 'sku', 'detalle', 'serial', 'proveedor', 'owner', 'factura', 'fcompra', 'vcompra', 'factivacion', 'accounted', 'vactual', 'location', 'building', 'floor', 'zona', 'city', 'country', 'estado', 'festado', 'usuarioinv', 'fingreso', 'fmodifica']},
        ),
        migrations.AddField(
            model_name='activos',
            name='sku',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
