# Generated by Django 5.2.5 on 2025-10-01 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohlag', '0005_alter_activos_options_activos_sku'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activos',
        ),
    ]
