# Generated by Django 5.2.5 on 2025-10-01 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohlag', '0006_delete_activos'),
        ('tablas', '0016_nombresareas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('0', 'ALL'), ('1', 'IT'), ('2', 'MO')], default='1', max_length=1)),
                ('newid', models.IntegerField(default=1)),
                ('sku', models.CharField(blank=True, max_length=45, null=True)),
                ('detalle', models.CharField(blank=True, max_length=250, null=True)),
                ('serial', models.CharField(blank=True, max_length=45, null=True)),
                ('owner', models.CharField(choices=[('0', 'OWN'), ('1', 'LEASE'), ('2', 'HAPAG-LLOYD CHILE SPA')], default='2', max_length=1)),
                ('factura', models.CharField(blank=True, max_length=45, null=True)),
                ('fcompra', models.DateField(blank=True, null=True)),
                ('vcompra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('factivacion', models.DateField(blank=True, null=True)),
                ('accounted', models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='1', max_length=1)),
                ('vactual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('floor', models.CharField(blank=True, max_length=15, null=True)),
                ('estado', models.CharField(choices=[('0', 'ASSIGNED'), ('1', 'DECOMMISSIONED'), ('2', 'IN USE'), ('3', 'NEW'), ('4', 'SPARE'), ('5', 'USED')], default='3', max_length=1)),
                ('festado', models.DateField(blank=True, null=True)),
                ('fingreso', models.DateTimeField(auto_now_add=True)),
                ('fmodifica', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.edificios')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.ciudades')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.paises')),
                ('fabricante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.fabricantes')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.modelos')),
                ('nombre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.nombresactivos')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.proveedores')),
                ('usuarioinv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.usuariosinventario')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.zonas')),
            ],
            options={
                'db_table': 'hlag_activos',
                'ordering': ['tipo', 'newid', 'nombre', 'modelo', 'fabricante', 'sku', 'detalle', 'serial', 'proveedor', 'owner', 'factura', 'fcompra', 'vcompra', 'factivacion', 'accounted', 'vactual', 'building', 'floor', 'zona', 'city', 'country', 'estado', 'festado', 'usuarioinv', 'fingreso', 'fmodifica'],
            },
        ),
    ]
