# Generated by Django 5.2.5 on 2025-10-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohlag', '0007_activos'),
    ]

    operations = [
        migrations.AddField(
            model_name='activos',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes'),
        ),
    ]
