# Generated by Django 5.2.5 on 2025-10-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohlag', '0008_activos_qr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activos',
            options={'ordering': ['tipo', 'newid', 'nombre', 'modelo', 'fabricante', 'sku', 'detalle', 'serial', 'proveedor', 'owner', 'factura', 'fcompra', 'vcompra', 'factivacion', 'accounted', 'vactual', 'building', 'floor', 'zona', 'city', 'country', 'estado', 'festado', 'usuarioinv', 'fingreso', 'fmodifica', 'qr']},
        ),
    ]
