# Generated by Django 5.2.5 on 2026-01-31 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohlag', '0009_alter_activos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activos',
            options={'ordering': ['tipo', 'newid', 'nombre', 'modelo', 'fabricante', 'sku', 'desc1', 'serial', 'proveedor', 'owner', 'factura', 'fcompra', 'vcompra', 'factivacion', 'accounted', 'vactual', 'building', 'floor', 'zona', 'city', 'country', 'estado', 'festado', 'usuarioinv', 'fingreso', 'fmodifica', 'qr']},
        ),
        migrations.RenameField(
            model_name='activos',
            old_name='detalle',
            new_name='desc1',
        ),
    ]
