# Generated by Django 5.2.5 on 2026-01-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohlag', '0010_alter_activos_options_rename_detalle_activos_desc1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activos',
            options={'ordering': ['tipo', 'newid', 'nombre', 'modelo', 'fabricante', 'sku', 'desc1', 'desc2', 'desc3', 'serial', 'proveedor', 'owner', 'factura', 'fcompra', 'vcompra', 'factivacion', 'accounted', 'vactual', 'building', 'floor', 'zona', 'city', 'country', 'estado', 'festado', 'usuarioinv', 'fingreso', 'fmodifica', 'qr']},
        ),
        migrations.AddField(
            model_name='activos',
            name='desc2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='activos',
            name='desc3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
