# Generated by Django 5.2.5 on 2025-08-29 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosPersonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('nombres', models.CharField(blank=True, max_length=90, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=90, null=True)),
                ('email', models.CharField(blank=True, max_length=90, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(choices=[('0', 'Bloqueado'), ('1', 'Habilitado')], default='1', max_length=1)),
                ('perfil', models.CharField(choices=[('0', 'administrador/'), ('1', 'usuarios/')], default='1', max_length=1)),
                ('cclave', models.PositiveSmallIntegerField(default=1)),
                ('token', models.CharField(blank=True, max_length=64, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios_personas',
                'ordering': ['username', 'nombres', 'apellidos', 'email', 'telefono', 'estado', 'perfil', 'cclave', 'usuario'],
            },
        ),
    ]
