# Generated by Django 5.2.5 on 2025-09-11 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0014_delete_activos'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariospersonas',
            options={'ordering': ['username', 'nombres', 'apellidos', 'email', 'pais', 'estado', 'perfil', 'cclave', 'pais', 'usuario']},
        ),
        migrations.RemoveField(
            model_name='usuariospersonas',
            name='telefono',
        ),
        migrations.AddField(
            model_name='usuariospersonas',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.paises'),
        ),
    ]
