# Generated by Django 5.2.5 on 2025-09-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuariospersonas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariospersonas',
            name='tipoactivo',
            field=models.CharField(choices=[('0', 'ALL'), ('1', 'IT'), ('2', 'MO')], default='0', max_length=1),
        ),
    ]
