# Generated by Django 5.2.5 on 2025-09-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuariospersonas_tipoactivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariospersonas',
            options={'ordering': ['username', 'nombres', 'apellidos', 'email', 'pais', 'estado', 'perfil', 'cclave', 'pais', 'usuario', 'tipoactivo']},
        ),
        migrations.AlterField(
            model_name='usuariospersonas',
            name='estado',
            field=models.CharField(choices=[('0', 'ENABLED'), ('1', 'DISABLED')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='usuariospersonas',
            name='perfil',
            field=models.CharField(choices=[('0', 'ADMINISTRADOR'), ('1', 'HLAG PEOPLE')], default='1', max_length=1),
        ),
    ]
