# Generated by Django 5.2.5 on 2025-09-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuariospersonas_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariospersonas',
            name='estado',
            field=models.CharField(choices=[('0', 'DISABLED'), ('1', 'ENABLED')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='usuariospersonas',
            name='perfil',
            field=models.CharField(choices=[('0', 'HLAG PEOPLE'), ('1', 'ADMINISTRADOR')], default='0', max_length=1),
        ),
    ]
