# Generated by Django 5.2.5 on 2025-09-24 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventariohlag', '0004_alter_areas_options_remove_areas_nombre_and_more'),
        ('usuarios', '0005_alter_usuariospersonas_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariospersonas',
            options={'ordering': ['username', 'nombres', 'apellidos', 'email', 'estado', 'perfil', 'tipoactivo', 'cclave', 'token', 'pais', 'area', 'usuario']},
        ),
        migrations.AddField(
            model_name='usuariospersonas',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventariohlag.areas'),
        ),
        migrations.AlterField(
            model_name='usuariospersonas',
            name='perfil',
            field=models.CharField(choices=[('0', 'NORMAL USER'), ('1', 'ADMINISTRADOR')], default='0', max_length=1),
        ),
    ]
