# Generated by Django 5.2.5 on 2025-10-15 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0016_nombresareas'),
        ('usuarios', '0007_alter_usuariospersonas_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariospersonas',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.nombresareas'),
        ),
    ]
