# Generated by Django 5.2.5 on 2025-08-27 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tablas_fabricantes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemsActivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tablas_items',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='NombresActivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tablas_nombresactivos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsuariosInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tablas_usuariosinventario',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tablas_zonas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas.fabricantes')),
            ],
            options={
                'db_table': 'tablas_modelos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Activos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('0', 'IT'), ('1', 'MO')], default='0', max_length=1)),
                ('identificador', models.CharField(max_length=45)),
                ('especificacion', models.IntegerField(blank=True, null=True)),
                ('detalle', models.CharField(blank=True, max_length=250, null=True)),
                ('serial', models.CharField(blank=True, max_length=45, null=True)),
                ('owner', models.CharField(choices=[('0', 'OWN'), ('1', 'LEASE'), ('2', 'HAPAG-LLOYD CHILE SPA')], default='2', max_length=1)),
                ('factura', models.CharField(blank=True, max_length=45, null=True)),
                ('fcompra', models.DateField(blank=True, null=True)),
                ('vcompra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factivacion', models.DateField(blank=True, null=True)),
                ('vactual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(choices=[('0', 'SCL'), ('1', 'VAP')], default='1', max_length=1)),
                ('building', models.CharField(choices=[('0', 'Nueva Cordova'), ('1', 'Work Marina')], default='1', max_length=1)),
                ('floor', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(choices=[('0', 'Santiago'), ('1', 'Viña del Mar')], default='1', max_length=1)),
                ('country', models.CharField(choices=[('0', 'Chile')], default='0', max_length=1)),
                ('estado', models.CharField(choices=[('0', 'Assigned'), ('1', 'Decommissioned'), ('2', 'In Use'), ('3', 'New'), ('4', 'Spare'), ('5', 'Used')], default='3', max_length=1)),
                ('festado', models.DateField(blank=True, null=True)),
                ('fingreso', models.DateTimeField(auto_now_add=True)),
                ('fmodifica', models.DateTimeField(auto_now=True)),
                ('fabricante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.fabricantes')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.itemsactivos')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.modelos')),
                ('nombre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.nombresactivos')),
                ('usuarioinv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.usuariosinventario')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.zonas')),
            ],
            options={
                'db_table': 'tablas_activos',
                'ordering': ['tipo', 'identificador', 'especificacion', 'nombre', 'modelo', 'fabricante', 'detalle', 'item', 'serial', 'owner', 'factura', 'fcompra', 'vcompra', 'factivacion', 'vactual', 'location', 'building', 'floor', 'zona', 'city', 'country', 'estado', 'festado', 'usuarioinv', 'fingreso', 'fmodifica'],
            },
        ),
    ]
