# Generated by Django 5.2.5 on 2025-09-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activos',
            options={'ordering': ['tipo', 'identificador', 'especificacion', 'nombre', 'modelo', 'fabricante', 'detalle', 'item', 'serial', 'proveedor', 'owner', 'factura', 'fcompra', 'vcompra', 'factivacion', 'vactual', 'location', 'building', 'floor', 'zona', 'city', 'country', 'estado', 'festado', 'usuarioinv', 'fingreso', 'fmodifica']},
        ),
        migrations.AddField(
            model_name='activos',
            name='accounted',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='activos',
            name='proveedor',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='activos',
            name='vactual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='activos',
            name='vcompra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
