# Generated by Django 5.2.5 on 2025-09-02 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0002_alter_activos_options_activos_accounted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activos',
            options={'ordering': ['tipo', 'identificador', 'especificacion', 'nombre', 'modelo', 'fabricante', 'detalle', 'item', 'serial', 'proveedor', 'owner', 'factura', 'fcompra', 'vcompra', 'factivacion', 'accounted', 'vactual', 'location', 'building', 'floor', 'zona', 'city', 'country', 'estado', 'festado', 'usuarioinv', 'fingreso', 'fmodifica']},
        ),
    ]
