# Generated by Django 5.2.5 on 2025-09-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0003_alter_activos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos',
            name='fcompra',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='activos',
            name='festado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
