# Generated by Django 5.2.5 on 2025-09-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0004_alter_activos_fcompra_alter_activos_festado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelos',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
    ]
