# Generated by Django 5.2.5 on 2025-09-03 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0005_alter_modelos_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelos',
            name='fabricante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablas.fabricantes'),
        ),
    ]
