# Generated by Django 5.2.5 on 2025-09-03 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0006_alter_modelos_fabricante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos',
            name='building',
            field=models.CharField(choices=[('0', 'NUEVA CORDOVA'), ('1', 'WORK MARINA')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='activos',
            name='city',
            field=models.CharField(choices=[('0', 'SANTIAGO'), ('1', 'VIÑA DEL MAR')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='activos',
            name='country',
            field=models.CharField(choices=[('0', 'CHILE')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='activos',
            name='estado',
            field=models.CharField(choices=[('0', 'ASSIGNED'), ('1', 'DECOMMISSIONED'), ('2', 'IN USE'), ('3', 'NEW'), ('4', 'SPARE'), ('5', 'USED')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='modelos',
            name='fabricante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.fabricantes'),
        ),
    ]
