# Generated by Django 5.2.5 on 2025-09-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0007_alter_activos_building_alter_activos_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelos',
            name='fabricante',
        ),
        migrations.AlterField(
            model_name='activos',
            name='fcompra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activos',
            name='festado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
