# Generated by Django 5.2.5 on 2025-09-03 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0008_remove_modelos_fabricante_alter_activos_fcompra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelos',
            name='fabricante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablas.fabricantes'),
        ),
    ]
