# Generated by Django 5.2.5 on 2025-09-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0009_modelos_fabricante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelos',
            options={'ordering': ['nombre', 'fabricante']},
        ),
    ]
