# Generated by Django 5.2.5 on 2025-09-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0010_alter_modelos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activos',
            name='accounted',
            field=models.CharField(choices=[('0', 'NO'), ('1', 'YES')], default='1', max_length=1),
        ),
    ]
