# Generated by Django 5.2.5 on 2025-09-10 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0011_alter_activos_accounted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activos',
            name='item',
        ),
        migrations.AlterModelOptions(
            name='activos',
            options={'ordering': ['tipo', 'identificador', 'nombre', 'modelo', 'fabricante', 'detalle', 'serial', 'proveedor', 'owner', 'factura', 'fcompra', 'vcompra', 'factivacion', 'accounted', 'vactual', 'location', 'building', 'floor', 'zona', 'city', 'country', 'estado', 'festado', 'usuarioinv', 'fingreso', 'fmodifica']},
        ),
        migrations.RemoveField(
            model_name='activos',
            name='especificacion',
        ),
        migrations.DeleteModel(
            name='ItemsActivos',
        ),
    ]
