# Generated by Django 5.2.5 on 2025-09-10 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0013_ciudades_paises_proveedores_edificios_ciudades_pais'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activos',
        ),
    ]
