# Generated by Django 5.2.5 on 2025-09-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0014_delete_activos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudades',
            options={'ordering': ['nombre', 'codigo', 'pais']},
        ),
        migrations.AlterModelOptions(
            name='paises',
            options={'ordering': ['nombre', 'codigo']},
        ),
        migrations.RemoveField(
            model_name='paises',
            name='clave',
        ),
        migrations.AddField(
            model_name='ciudades',
            name='codigo',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='paises',
            name='codigo',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
