# Generated by Django 5.2.5 on 2025-09-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablas', '0015_alter_ciudades_options_alter_paises_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombresAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tablas_nombresareas',
                'ordering': ['nombre'],
            },
        ),
    ]
